server:
    port: 8081
    servlet:
        context-path: /security
spring:
    application:
        name: security
    datasource:
        url: jdbc:mysql://@localhost:3306/permission?useUnicode=true&characterEncoding=utf8&useSSL=false
        data-password: root
        data-username: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    jackson:
            time-zone: GMT+8
            date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

